<!DOCTYPE HTML>
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <title>Meteo</title>
   </head>
   <body>
      <ul>
         <li>Date mesure : 2025-11-16</li>
      </ul>
      <table border="1" width="90%">
         <tr>
            <th>ville</th>
            <th>Température</th>
         </tr>
         <tr>
            <td>Casablanca</td>
            <td>22</td>
         </tr>
         <tr>
            <td>Mohammedia</td>
            <td>23</td>
         </tr>
         <tr>
            <td>Marrakech</td>
            <td>32</td>
         </tr>
         <tr>
            <td>Tanger</td>
            <td>25</td>
         </tr>
         <tr>
            <td>El jadida</td>
            <td>26</td>
         </tr>
         <tr>
            <td>Laayoune</td>
            <td>34</td>
         </tr>
         <tr>
            <td>Ouarzazate</td>
            <td>36</td>
         </tr>
         <tr>
            <td>Dakhla</td>
            <td>34</td>
         </tr>
         <tr>
            <td>Oujda</td>
            <td>34</td>
         </tr>
      </table>
      <ul>
         <li>Date mesure : 2025-11-17</li>
      </ul>
      <table border="1" width="90%">
         <tr>
            <th>ville</th>
            <th>Température</th>
         </tr>
         <tr>
            <td>Casablanca</td>
            <td>20</td>
         </tr>
         <tr>
            <td>Mohammedia</td>
            <td>21</td>
         </tr>
         <tr>
            <td>Marrakech</td>
            <td>30</td>
         </tr>
         <tr>
            <td>Tanger</td>
            <td>28</td>
         </tr>
         <tr>
            <td>El jadida</td>
            <td>27</td>
         </tr>
         <tr>
            <td>Laayoune</td>
            <td>32</td>
         </tr>
         <tr>
            <td>Ouarzazate</td>
            <td>32</td>
         </tr>
         <tr>
            <td>Dakhla</td>
            <td>34</td>
         </tr>
         <tr>
            <td>Oujda</td>
            <td>28</td>
         </tr>
      </table>
   </body>
</html>